/** Copy medium détail lieu (MEDIUM-LIEUX-DETAIL-01). Réutilise le desktop là où la maquette est identique. */

export {
  PLACE_DETAIL_DESKTOP_ABOUT_COLLAPSE as PLACE_DETAIL_MEDIUM_ABOUT_COLLAPSE,
  PLACE_DETAIL_DESKTOP_ABOUT_EXPAND as PLACE_DETAIL_MEDIUM_ABOUT_EXPAND,
  PLACE_DETAIL_DESKTOP_ABOUT_TITLE as PLACE_DETAIL_MEDIUM_ABOUT_TITLE,
  PLACE_DETAIL_DESKTOP_ACCESSIBLE as PLACE_DETAIL_MEDIUM_ACCESSIBLE,
  PLACE_DETAIL_DESKTOP_ADDRESS_TITLE as PLACE_DETAIL_MEDIUM_ADDRESS_TITLE,
  PLACE_DETAIL_DESKTOP_BACK as PLACE_DETAIL_MEDIUM_BACK,
  PLACE_DETAIL_DESKTOP_CONTACT_TITLE as PLACE_DETAIL_MEDIUM_CONTACT_TITLE,
  PLACE_DETAIL_DESKTOP_EVENT_CTA as PLACE_DETAIL_MEDIUM_EVENT_CTA,
  PLACE_DETAIL_DESKTOP_EVENTS_EMPTY as PLACE_DETAIL_MEDIUM_EVENTS_EMPTY,
  PLACE_DETAIL_DESKTOP_GALLERY as PLACE_DETAIL_MEDIUM_GALLERY,
  PLACE_DETAIL_DESKTOP_HOURS_EMPTY as PLACE_DETAIL_MEDIUM_HOURS_EMPTY,
  PLACE_DETAIL_DESKTOP_HOURS_TITLE as PLACE_DETAIL_MEDIUM_HOURS_TITLE,
  PLACE_DETAIL_DESKTOP_HOURS_TODAY as PLACE_DETAIL_MEDIUM_HOURS_TODAY,
  PLACE_DETAIL_DESKTOP_HOURS_VIEW_ALL as PLACE_DETAIL_MEDIUM_HOURS_VIEW_ALL,
  PLACE_DETAIL_DESKTOP_KNOW_TITLE as PLACE_DETAIL_MEDIUM_KNOW_TITLE,
  PLACE_DETAIL_DESKTOP_MAP as PLACE_DETAIL_MEDIUM_MAP,
  PLACE_DETAIL_DESKTOP_NEARBY_MAP as PLACE_DETAIL_MEDIUM_NEARBY_MAP,
  PLACE_DETAIL_DESKTOP_NEARBY_TITLE as PLACE_DETAIL_MEDIUM_NEARBY_TITLE,
  PLACE_DETAIL_DESKTOP_NEARBY_VIEW_ALL as PLACE_DETAIL_MEDIUM_NEARBY_VIEW_ALL,
  PLACE_DETAIL_DESKTOP_NEARBY_VIEW_PLACE as PLACE_DETAIL_MEDIUM_NEARBY_VIEW_PLACE,
  PLACE_DETAIL_DESKTOP_NOW_TITLE as PLACE_DETAIL_MEDIUM_NOW_TITLE,
  PLACE_DETAIL_DESKTOP_NOW_VIEW_ALL as PLACE_DETAIL_MEDIUM_NOW_VIEW_ALL,
  PLACE_DETAIL_DESKTOP_OPEN_MAP as PLACE_DETAIL_MEDIUM_OPEN_MAP,
  PLACE_DETAIL_DESKTOP_PHOTOS_TITLE as PLACE_DETAIL_MEDIUM_PHOTOS_TITLE,
  PLACE_DETAIL_DESKTOP_PHOTOS_VIEW_ALL as PLACE_DETAIL_MEDIUM_PHOTOS_VIEW_ALL,
  PLACE_DETAIL_DESKTOP_RELATION_EMPTY as PLACE_DETAIL_MEDIUM_RELATION_EMPTY,
  PLACE_DETAIL_DESKTOP_RELATION_TITLE as PLACE_DETAIL_MEDIUM_RELATION_TITLE,
  PLACE_DETAIL_DESKTOP_REPORT_CHANGE as PLACE_DETAIL_MEDIUM_REPORT_CHANGE,
  PLACE_DETAIL_DESKTOP_REPORT_SOON as PLACE_DETAIL_MEDIUM_REPORT_SOON,
  PLACE_DETAIL_DESKTOP_REPORT_SUGGEST as PLACE_DETAIL_MEDIUM_REPORT_SUGGEST,
  PLACE_DETAIL_DESKTOP_REPORT_TITLE as PLACE_DETAIL_MEDIUM_REPORT_TITLE,
  PLACE_DETAIL_DESKTOP_ROUTE as PLACE_DETAIL_MEDIUM_ROUTE,
  PLACE_DETAIL_DESKTOP_SAVE as PLACE_DETAIL_MEDIUM_SAVE,
  PLACE_DETAIL_DESKTOP_SAVE_SOON as PLACE_DETAIL_MEDIUM_SAVE_SOON,
  PLACE_DETAIL_DESKTOP_SHARE as PLACE_DETAIL_MEDIUM_SHARE,
  PLACE_DETAIL_DESKTOP_SHARE_COPIED as PLACE_DETAIL_MEDIUM_SHARE_COPIED,
  PLACE_DETAIL_DESKTOP_TAB_EVENTS as PLACE_DETAIL_MEDIUM_TAB_EVENTS,
  PLACE_DETAIL_DESKTOP_TAB_OVERVIEW as PLACE_DETAIL_MEDIUM_TAB_OVERVIEW,
  PLACE_DETAIL_DESKTOP_TAB_PRACTICAL as PLACE_DETAIL_MEDIUM_TAB_PRACTICAL,
  PLACE_DETAIL_DESKTOP_TAB_PUBLICATIONS as PLACE_DETAIL_MEDIUM_TAB_PUBLICATIONS,
  PLACE_DETAIL_DESKTOP_VERIFIED as PLACE_DETAIL_MEDIUM_VERIFIED,
  PLACE_DETAIL_DESKTOP_VISITED as PLACE_DETAIL_MEDIUM_VISITED,
  PLACE_DETAIL_DESKTOP_VISITED_SOON as PLACE_DETAIL_MEDIUM_VISITED_SOON,
  PLACE_DETAIL_DESKTOP_WEBSITE as PLACE_DETAIL_MEDIUM_WEBSITE,
  PLACE_DETAIL_DESKTOP_WHY_TITLE as PLACE_DETAIL_MEDIUM_WHY_TITLE,
} from "./place-detail-desktop-labels";

export const PLACE_DETAIL_MEDIUM_HOURS_FOOTER =
  "Vérifiez les horaires avant votre déplacement.";
export const PLACE_DETAIL_MEDIUM_REPORT_BODY =
  "Aidez-nous à maintenir des informations fiables.";
export const PLACE_DETAIL_MEDIUM_CONTACT_OFFICIAL = "Site officiel";
export const PLACE_DETAIL_MEDIUM_CONTACT_CALL = "Contacter le lieu";
