/** Copy mobile détail lieu (MOBILE-LIEUX-DETAIL-01). Réutilise le desktop là où identique. */

export {
  PLACE_DETAIL_DESKTOP_ABOUT_COLLAPSE as PLACE_DETAIL_MOBILE_ABOUT_COLLAPSE,
  PLACE_DETAIL_DESKTOP_ABOUT_EXPAND as PLACE_DETAIL_MOBILE_ABOUT_EXPAND,
  PLACE_DETAIL_DESKTOP_ABOUT_TITLE as PLACE_DETAIL_MOBILE_ABOUT_TITLE,
  PLACE_DETAIL_DESKTOP_ACCESSIBLE as PLACE_DETAIL_MOBILE_ACCESSIBLE,
  PLACE_DETAIL_DESKTOP_ADDRESS_TITLE as PLACE_DETAIL_MOBILE_ADDRESS_TITLE,
  PLACE_DETAIL_DESKTOP_BACK as PLACE_DETAIL_MOBILE_BACK,
  PLACE_DETAIL_DESKTOP_CONTACT_TITLE as PLACE_DETAIL_MOBILE_CONTACT_TITLE,
  PLACE_DETAIL_DESKTOP_EVENT_CTA as PLACE_DETAIL_MOBILE_EVENT_CTA,
  PLACE_DETAIL_DESKTOP_EVENTS_EMPTY as PLACE_DETAIL_MOBILE_EVENTS_EMPTY,
  PLACE_DETAIL_DESKTOP_HOURS_EMPTY as PLACE_DETAIL_MOBILE_HOURS_EMPTY,
  PLACE_DETAIL_DESKTOP_HOURS_TITLE as PLACE_DETAIL_MOBILE_HOURS_TITLE,
  PLACE_DETAIL_DESKTOP_HOURS_TODAY as PLACE_DETAIL_MOBILE_HOURS_TODAY,
  PLACE_DETAIL_DESKTOP_HOURS_VIEW_ALL as PLACE_DETAIL_MOBILE_HOURS_VIEW_ALL,
  PLACE_DETAIL_DESKTOP_KNOW_TITLE as PLACE_DETAIL_MOBILE_KNOW_TITLE,
  PLACE_DETAIL_DESKTOP_MAP as PLACE_DETAIL_MOBILE_MAP,
  PLACE_DETAIL_DESKTOP_NEARBY_MAP as PLACE_DETAIL_MOBILE_NEARBY_MAP,
  PLACE_DETAIL_DESKTOP_NEARBY_TITLE as PLACE_DETAIL_MOBILE_NEARBY_TITLE,
  PLACE_DETAIL_DESKTOP_NEARBY_VIEW_PLACE as PLACE_DETAIL_MOBILE_NEARBY_VIEW_PLACE,
  PLACE_DETAIL_DESKTOP_NOW_TITLE as PLACE_DETAIL_MOBILE_NOW_TITLE,
  PLACE_DETAIL_DESKTOP_OPEN_MAP as PLACE_DETAIL_MOBILE_OPEN_MAP,
  PLACE_DETAIL_DESKTOP_PHOTOS_TITLE as PLACE_DETAIL_MOBILE_PHOTOS_TITLE,
  PLACE_DETAIL_DESKTOP_PHOTOS_VIEW_ALL as PLACE_DETAIL_MOBILE_PHOTOS_VIEW_ALL,
  PLACE_DETAIL_DESKTOP_RELATION_EMPTY as PLACE_DETAIL_MOBILE_RELATION_EMPTY,
  PLACE_DETAIL_DESKTOP_RELATION_TITLE as PLACE_DETAIL_MOBILE_RELATION_TITLE,
  PLACE_DETAIL_DESKTOP_REPORT_CHANGE as PLACE_DETAIL_MOBILE_REPORT_CHANGE,
  PLACE_DETAIL_DESKTOP_REPORT_SOON as PLACE_DETAIL_MOBILE_REPORT_SOON,
  PLACE_DETAIL_DESKTOP_REPORT_SUGGEST as PLACE_DETAIL_MOBILE_REPORT_SUGGEST,
  PLACE_DETAIL_DESKTOP_REPORT_TITLE as PLACE_DETAIL_MOBILE_REPORT_TITLE,
  PLACE_DETAIL_DESKTOP_ROUTE as PLACE_DETAIL_MOBILE_ROUTE,
  PLACE_DETAIL_DESKTOP_SAVE as PLACE_DETAIL_MOBILE_SAVE,
  PLACE_DETAIL_DESKTOP_SAVE_SOON as PLACE_DETAIL_MOBILE_SAVE_SOON,
  PLACE_DETAIL_DESKTOP_SHARE as PLACE_DETAIL_MOBILE_SHARE,
  PLACE_DETAIL_DESKTOP_SHARE_COPIED as PLACE_DETAIL_MOBILE_SHARE_COPIED,
  PLACE_DETAIL_DESKTOP_TAB_EVENTS as PLACE_DETAIL_MOBILE_TAB_EVENTS,
  PLACE_DETAIL_DESKTOP_TAB_PUBLICATIONS as PLACE_DETAIL_MOBILE_TAB_PUBLICATIONS,
  PLACE_DETAIL_DESKTOP_VERIFIED as PLACE_DETAIL_MOBILE_VERIFIED,
  PLACE_DETAIL_DESKTOP_VISITED as PLACE_DETAIL_MOBILE_VISITED,
  PLACE_DETAIL_DESKTOP_VISITED_SOON as PLACE_DETAIL_MOBILE_VISITED_SOON,
  PLACE_DETAIL_DESKTOP_WHY_TITLE as PLACE_DETAIL_MOBILE_WHY_TITLE,
} from "./place-detail-desktop-labels";

export const PLACE_DETAIL_MOBILE_TAB_OVERVIEW = "Aperçu";
export const PLACE_DETAIL_MOBILE_TAB_PRACTICAL = "Informations";

export const PLACE_DETAIL_MOBILE_GALLERY = (count: number) =>
  count > 1 ? `${count} photos` : "1 photo";

export const PLACE_DETAIL_MOBILE_HOURS_FOOTER =
  "Vérifiez les horaires avant votre déplacement.";
export const PLACE_DETAIL_MOBILE_REPORT_BODY =
  "Aidez-nous à maintenir des informations fiables.";
export const PLACE_DETAIL_MOBILE_CONTACT_OFFICIAL = "Site officiel";
export const PLACE_DETAIL_MOBILE_CONTACT_CALL = "Contacter le lieu";

/** @deprecated MOBILE-LIEUX-02 — utiliser PLACE_DETAIL_MOBILE_TAB_OVERVIEW */
export const PLACE_DETAIL_MOBILE_TAB_ABOUT = "À propos";
/** @deprecated MOBILE-LIEUX-02 */
export const PLACE_DETAIL_MOBILE_TAB_REVIEWS = "Avis";
/** @deprecated MOBILE-LIEUX-02 */
export const PLACE_DETAIL_MOBILE_TAB_OFFERS = "Offres";
/** @deprecated MOBILE-LIEUX-02 */
export const PLACE_DETAIL_MOBILE_TAB_PHOTOS = "Photos";

export const PLACE_DETAIL_MOBILE_BOOKMARK = "Enregistrer";
export const PLACE_DETAIL_MOBILE_BOOKMARK_SOON = "Enregistrer — bientôt disponible";

export const PLACE_DETAIL_MOBILE_QUICK_ADDRESS = "Adresse";
export const PLACE_DETAIL_MOBILE_QUICK_WEBSITE = "Site web";
export const PLACE_DETAIL_MOBILE_QUICK_NEIGHBORHOOD = "Quartier";
export const PLACE_DETAIL_MOBILE_QUICK_ROUTE = "Itinéraire";

export const PLACE_DETAIL_MOBILE_PHOTOS_CTA = (count: number) =>
  count === 1 ? "Voir la photo" : `Voir les photos (${count})`;

export const PLACE_DETAIL_MOBILE_MAP_CTA = "Voir sur la carte";
export const PLACE_DETAIL_MOBILE_MAP_LOCATE = "Centrer sur ma position";

export const PLACE_DETAIL_MOBILE_REVIEWS_EMPTY =
  "Les avis sur ce lieu seront disponibles prochainement.";
export const PLACE_DETAIL_MOBILE_OFFERS_EMPTY =
  "Aucune offre en cours pour ce lieu pour l'instant.";
export const PLACE_DETAIL_MOBILE_PHOTOS_EMPTY = "Aucune photo supplémentaire pour ce lieu.";
export const PLACE_DETAIL_MOBILE_PUBLICATIONS_EMPTY =
  "Les publications liées à ce lieu apparaîtront ici.";
export const PLACE_DETAIL_MOBILE_ABOUT_EMPTY =
  "La description de ce lieu sera bientôt enrichie.";

export const PLACE_DETAIL_MOBILE_POST_CTA = "Publier quelque chose";
export const PLACE_DETAIL_MOBILE_FAVORITE = "Ajouter aux favoris";
export const PLACE_DETAIL_MOBILE_FAVORITE_SOON = "Favoris — bientôt disponible";
export const PLACE_DETAIL_MOBILE_BADGE_FEATURED = "À la une";
